services:
  - type: web
    name: banking-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CI_ENVIRONMENT
        value: production
      - key: DATABASE_DEFAULT_HOSTNAME
        sync: false
      - key: DATABASE_DEFAULT_DATABASE
        sync: false
      - key: DATABASE_DEFAULT_USERNAME
        sync: false
      - key: DATABASE_DEFAULT_PASSWORD
        sync: false
      - key: APP_BASE_URL
        sync: false
      - key: EMAIL_FROM_EMAIL
        sync: false
      - key: EMAIL_FROM_NAME
        sync: false
      - key: EMAIL_SMTP_HOST
        sync: false
      - key: EMAIL_SMTP_USER
        sync: false
      - key: EMAIL_SMTP_PASS
        sync: false
      - key: EMAIL_SMTP_PORT
        value: "587"
      - key: EMAIL_SMTP_CRYPTO
        value: "tls"
      - key: ENCRYPTION_KEY
        sync: false
    healthCheckPath: /
    buildCommand: docker build -t banking-app .
    startCommand: docker run -p $PORT:80 banking-app 